Update MapLibre GL Native for Android and other things
maplibre/maplibre-plugins-android pull request #21
Opened 2023-03-01 11:28 UTC by louwers

- Updated Android Gradle Plugin
- Update kotlin-android-extensions (and view bindings)
- Updated Kotlin
- Updated MapLibre GL Native for Android
- Removed `Style.MAPBOX_STREETS` etc., use `Style.getPredefinedStyle` instead (using MapTiler).

The test app build and runs again. But every activity needs to have a well known tile server set explicitly to function. I only updated the BulkSymbolActivity now. The markers do not appear yet but as soon as that is fixed I would like to merge this.

2023-03-14 13:03 UTC, fynngodau commented
> But every activity needs to have a well known tile server set explicitly to function.

Possibly it might be a good idea to subclass Activity / `AppCompatActivity` and call `Mapbox.getInstance` in that new superclass' `onCreate`?

> I only updated the BulkSymbolActivity now. The markers do not appear yet but as soon as that is fixed I would like to merge this.

The problem is here:

https://github.com/maplibre/maplibre-plugins-android/blob/e81c1bbb969150dfd623c9567ae3b2c083b9178d/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/BulkSymbolActivity.java#L158

The icon `fire-station-11` is undefined because you changed the map's style. We can add such an icon again and then it will work again :) [Here is a patch]([fix-symbols.patch](https://github.com/maplibre/maplibre-plugins-android/files/10968791/fix-symbols.patch.txt)) that uses the fire hydrant icon from Google's material design and gets us the icons back:

![the-icons-are-back](https://user-images.githubusercontent.com/16943720/225008460-07de3f64-3524-4be6-ad1d-2ec5e0d1a642.png)

2023-03-14 13:10 UTC, fynngodau requested changes
Is there a specific reason you changed the indent in some of the files? Was it misaligned across the different files?

2023-03-14 18:09 UTC, louwers commented on app/build.gradle
> +    buildConfigField('String', 'MAPTILER_API_KEY', project.findProperty("maptilerApiKey") ?: '""')
Good call.

2023-03-14 18:10 UTC, louwers commented
@fynngodau Wow thanks with the icon!!

Good catch.

2023-03-25 19:35 UTC, ovivoda commented on app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/ktx/maps/MapboxKtxActivity.kt
> +    setContentView(view)
you can just `setContentView(binding.root)`

2023-03-25 19:44 UTC, ovivoda commented on app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/localization/LocalizationActivity.kt
>      setContentView(R.layout.activity_localization)
do binding first then setContentView(binding.root)

2023-03-25 19:51 UTC, ovivoda commented on app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/scalebar/ScalebarActivity.kt
> +    mapView = findViewById<View>(R.id.mapView) as MapView
same as above just use binding instead of findViewById

2023-03-25 19:52 UTC, ovivoda commented on app/src/main/res/layout/activity_scalebar.xml
> +        app:maplibre_cameraTargetLat="37.769145"
nice to see maplibre here!

2023-05-07 18:59 UTC, merged